### PR TITLE
Fix bug in initialization of allowed values

### LINKED ISSUE #42: Incorrect variable values being passed to modules
**Expected behavior**

Module is planned with variable values defined in the module config

**Actual behavior**

Module is planned with some variable values defined for the current module and some for the next one

**Steps to reproduce**

astro.yaml
```
---

terraform:
      version: 0.11.7

modules:
  - name: bar 
    path: ./bar
    remote:
      backend: local
      backend_config:
        path: /tmp/terraform-tests/bar-{{.environment}}.tfstate
    variables:
      - name: environment
        values: [dev, staging, prod]

  - name: foo 
    path: ./foo
    remote:
      backend: local
      backend_config:
        path: /tmp/terraform-tests/foo-{{.environment}}.tfstate
    variables:
      - name: environment
        values: [mgmt]
```
foo/terraform.tf
```
terraform {
  backend "local" {}
}

resource "null_resource" "foo" {}
```
bar/terraform.tf
```
terraform {
  backend "local" {}
}

resource "null_resource" "bar" {}
```

astro plan
```
foo-mgmt: OK Changes (0s)

  + null_resource.foo
      id: <computed>


bar-mgmt: OK Changes (0s)

  + null_resource.bar
      id: <computed>


bar-dev: OK Changes (0s)

  + null_resource.bar
      id: <computed>


bar-prod: OK Changes (0s)

  + null_resource.bar
      id: <computed>


Done
```

`bar-mgmt` is planned instead of `bar-staging` in the plan above.

### PR DESCRIPTION
**Pull request by btromanova**
This fixes #42.

The bug was in copying reference of array containing values from config into array containing all allowed values. The latter was then modified (by adding values and sorting), which caused items in the values array to change.

This PR replaces copy by reference to creation of new array and coping values and modifies test to go through the previously failing scenario.

### CODE REVIEW

File: astro/cli/astro/cmd/flags_test.go [hunk 1]
```diff
@@ -87,6 +87,12 @@ func TestPlanAllowedValues(t *testing.T) {
 		"staging",
 		"prod",
 	}
+	expectedModules := map[string][]string{
```
Comment (DragonZ) [inline astro/cli/astro/cmd/flags_test.go]: Please merge input and output into table driven tests style, for example,
```go
testcases := []struct {
		msg      string
		input    string
		expected []string
	}{
		{
			msg:      "environment is dev",
			input:    "dev",
			expected: []string{"misc-dev", "test_env-dev"},
		},
		{
			msg:      "environment is mgmt",
			input:    "mgmt",
			expected: []string{"foo_mgmt-mgmt"},
		},
                // add additional test cases here
	}

	for _, tt := range testcases {
		t.Run(tt.msg, func(t *testing.T) {
			result := tests.RunTest(t, []string{
				"--config=merge_values.yaml",
				"plan",
				"--environment",
				tt.input,
			}, "fixtures/flags", tests.VERSION_LATEST)
			// Check that all expected modules were planned for environment env
			for _, module := range tt.expected {
				assert.Contains(t, result.Stdout.String(), module)
			}

			assert.Equal(t, 0, result.ExitCode)
		})
	}
```

Comment (btromanova) [reply astro/cli/astro/cmd/flags_test.go]: Done, please take another look.
