### PR TITLE
Fix zip slip vulnerability

### LINKED ISSUE #46: Potential
Hey Astro team,
  We found a potentially vulnerable function to the Zip Slip vulnerability. The idea of the vulnerability is that by triggering a path transversal on a zip file you are able to write files outside of your folder (https://cwe.mitre.org/data/definitions/29.html)
  Here is the vulnerable function:
  https://github.com/uber/astro/blob/master/astro/tvm/utils.go#L69

  We are well aware, that downloads files passed to unzip only occur from a specific URL provided by astro, so the risk is really low,  but we thought we should let you know about the potential risk.

Regards
Semmle Security Team
Discovered by Max Schaefer

### PR DESCRIPTION
**Pull request by dansimau**
This fixes an issue where files within a zip file can break out of the target directory when being extracted.

Fixes #46.

### CODE REVIEW

File: astro/tvm/utils.go [hunk 1]
```diff
@@ -67,6 +69,9 @@ func unzip(zipfilePath string, destDir string) error {
 		defer fh.Close()
 
 		path := filepath.Join(destDir, f.Name)
+		if !strings.HasPrefix(path, filepath.Clean(destDir)+string(os.PathSeparator)) {
```
Comment (shivamdixit) [inline astro/tvm/utils.go]: This is good, however, as others pointed out in https://github.com/golang/go/issues/25849, the check can still bypassed by symlinks. Although the symlink is implemented in tar and not in Zip, so it should be okay.

Comment (shivamdixit) [reply astro/tvm/utils.go]: A small note: This relies on `Join` performing a `Clean` on the path. Imagine if that doesn't happen any longer, then the check will be basically useless. For example:
```
path := "/home/friendly/../../etc/shadow"
strings.HasPrefix(path, "/home/friendly/") == true
```

An explicit Clean before comparison wouldn't harm.

Comment (jcorbin) [reply astro/tvm/utils.go]: Since that would be an observable change to the `filepath.Join` api (it not calling Clean), the chances of that ever happening are next to 0. It's not just observable, it's actually documented `Join calls Clean on the result` say [the docs](https://golang.org/pkg/path/filepath/#Join), so it'd actually be a violation of the Go 1.x compatibility contract to change it.

**Comment by jcorbin** [comment]
Fwiw, I have a need to implement similar zip extraction, here's the code I ended up with: https://gist.github.com/jcorbin/fd0716bd0bc4c49cd22d73e4aad23b38

- extracts in GOMAXPROCS-parallel
- slightly better reliability / error flow in the file extraction path
- slightly better file permission restoration
- more efficient for large archives, since it uses `io.CopyBuffer` internally with a re-used buffer, rather than `io.Copy` dynamically allocated a 32KB buffer for every extracted file (causing GC pressure scaling with size of archive)

File: astro/tvm/utils.go (hunk 1 above)
Comment (dansimau) [reply astro/tvm/utils.go]: Agree with @jcorbin, gonna leave it
